### Создание компании
POST localhost:8080/companies
Content-Type: application/json

{
  "name": "МТест",
  "inn": "1234567890",
  "kpp": "123456789"
}

### Получение списка всех компаний
GET localhost:8080/companies
Accept: application/json

### Получение компании по id с проекцией
GET localhost:8080/companies/2715e481-dff6-4405-ad5c-fb14aa07bd7c?projection=companyInfo
Accept: application/json

### Изменение имени компании по id
PATCH localhost:8080/companies/528d4c61-6cda-4d12-9a0a-89adf91e0651
Content-Type: application/json

{
  "name": "Супертех"
}

### Изменение компании по id
PUT localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe
Content-Type: application/json

{
  "name": "МегаСупертех",
  "inn": "0987654321",
  "kpp": "987654321"
}

### Удаление компании по id
DELETE localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe

### Получение инфы о API
GET localhost:8080/

### Получение профилей
GET http://localhost:8080/profile
Accept: application/json

### Получение схемы компании
GET http://localhost:8080/profile/companies
Accept: application/json

### Создание департамента
POST localhost:8080/departments
Content-Type: application/json

{
  "name": "Отдел backend-разработки"
}

### Линковка отдела к компании
PUT http://localhost:8080/departments/ed16b778-8d93-4a10-9029-adc6b7e7dad8/company
Content-Type: text/uri-list

http://localhost:8080/companies/2715e481-dff6-4405-ad5c-fb14aa07bd7c