### Создание компании
POST localhost:8080/companies
Content-Type: application/json

{
  "name": "Инфратех",
  "inn": "1234567890",
  "kpp": "123456789"
}

### Получение списка всех компаний с пагинацией
GET localhost:8080/companies?page=1&size=5
Accept: application/json

### Получение компании по UUID
GET localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe
Accept: application/json

### Изменение имени компании по UUID
PATCH localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe
Content-Type: application/json

{
  "name": "Супертех"
}

### Изменение компании по UUID
PUT localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe
Content-Type: application/json

{
  "name": "МегаСупертех",
  "inn": "0987654321",
  "kpp": "987654321"
}

### Удаление компании по UUID
DELETE localhost:8080/companies/cbf309f1-21e8-47bc-a42b-b91a083011fe

### Получение инфы о API
GET localhost:8080/

### Получение профилей
GET http://localhost:8080/profile
Accept: application/json

### Получение схемы компании
GET http://localhost:8080/profile/companies
Accept: application/json